# Generated by Django 5.1.1 on 2024-11-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='showlistproduct/')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
